# Generated by Django 4.2.1 on 2023-05-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='tutle',
            new_name='title',
        ),
    ]
